language: go

after_success:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
  - stage: test
    script: make test
    go: "1.13.x"
    env: GO111MODULE=auto

  - stage: test
    script: make test
    go: "1.12.x"
    env: GO111MODULE=auto

  - stage: test
    go: "1.11.x"
    script:
    - make exec CMD="go get -t"
    - make test
    env: GO111MODULE=off

  - stage: test
    go: "1.10.x"
    script:
    - make exec CMD="go get -t"
    - make test
    env: USE_GLOBAL_GOPATH=1

  - stage: test
    go: "1.9.x"
    script:
    - make exec CMD="go get -t"
    - make test
    env: USE_GLOBAL_GOPATH=1